### ISSUE TITLE
Switch button

### ISSUE THREAD

**Issue by tiagoclc** [dukeduck1984/Hydrometer-Esp32-Micropython#7]
To switch mode, how about use "boot" button? Its on gpio 0.

hardware_config.json:

  "mode_pin": 0,

**Comment by tiagoclc** [comment]
Are you comfortable with me getting into your work without been called?

**Comment by dukeduck1984** [comment]
well, there is no boot button on the esp32 board i'm using.  of course you can make the change on your side if you see this fits your needs.
